name: 'Version check'
branding:
  icon: package
  color: green
description: 'Updates a gist with the tauri latest.json build artifact'
inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node20'
  main: 'lib/index.js'
