name: 'Post release'
branding:
  icon: package
  color: green
description: 'A GitHub action that refines the tauri release and updates a gist with the tauri latest.json build artifact'
inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node20'
  main: 'lib/index.js'
