import { Element, Root } from 'hast';

// import { visit } from 'unist-util-visit';

export function addFooter() {
  return (tree: Root) => {
    const footer: Element = {
      type: 'element',
      tagName: 'footer',
      properties: {},
      children: [
        {
          type: 'text',
          value: 'This coursework was generated by ',
        },
        {
          type: 'element',
          tagName: 'a',
          properties: {
            href: 'https://github.com/dmca-glasgow/isos',
            target: '_blank',
          },
          children: [
            {
              type: 'text',
              value: 'ISOS',
            },
          ],
        },
        {
          type: 'text',
          value:
            ', an open-source project developed at the University of Glasgow.',
        },
      ],
    };
    tree.children.push(footer);

    // visit(tree, 'root', (node) => {
    //   if (node.children.length) {
    //     const first = node.children[0];
    //     console.log(node, node.children);
    //     if (first.type === 'element' && first.tagName === 'article') {
    //       const footer: Element = {
    //         type: 'element',
    //         tagName: 'footer',
    //         properties: {},
    //         children: [],
    //       };
    //       console.log(footer);
    //       first.children.push(footer);
    //     }
    //   }
    // });
  };
}
